version: '3.8'
services:
  db:
    image: postgres:15
    container_name: inflearn_clone
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inflearn_clone
    volumes:
      - inflearn_clone_db:/var/lib/postgresql/data

volumes:
  inflearn_clone_db:
